CREATE SCHEMA Chat
create table messages (id integer generated by default as identity, text varchar(255), time date, receiver integer, sender integer, primary key (id))
create table users (id integer generated by default as identity, access_token varchar(255), name varchar(255), primary key (id))
alter table messages add constraint FKpmq5ifuu12ky74d5hbouj2gxn foreign key (receiver) references users
alter table messages add constraint FK9fqml4keo3c2rtevghw3guhh7 foreign key (sender) references users
